# Generated by Django 2.1.5 on 2019-03-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_auto_20190319_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.Comment'),
        ),
    ]
